name = "NormalizingFlowsTutorials"
uuid = "1c161123-2726-431d-93d3-ddc6c05c22d1"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
